---
- name: Use mariadb role playbook 
  hosts: test
  become: true
  
  pre_tasks:
    - name: pre_tasks message 
      debug:
        msg: 'Starting Wagtail setup with UWSGI and NGINX'

  roles:
    - role: mariadb
      mariadb_root_password: "{{ db_root_pass }}"
      mariadb_databases:
        - name : "{{ db.name }}"
      mariadb_users:
        - name: "{{ db_user.name }}"
          password: "{{ db_user.password }}"
          priv: "{{ db_user.priv }}"
          host: "{{ db_user.host }}"
          
    - role: wagtail
      project_name: "{{ proj_name }}"
      project_path: "{{ proj_path }}"
      database:
        - name: "{{ db.name }}"
          user: "{{ db_user.name }}"
          password: "{{ db_user.password }}"
          hostname: "{{ db_user.hostname }}"
          port: "{{ db_user.port }}"

    - role: nginx
      project_name: "{{ proj_name }}"
      project_path: "{{ proj_path }}"
  
  post_tasks:
    - name: post_tasks message 
      debug:
        msg: 'Starting Wagtail setup with UWSGI and NGINX. Server Reboot might be required for selinux changes to take effect.'