# roles/mariadb/tasks/main.yml
---

- include_vars:
    file: main.yml

- include_tasks: install.yml
- include_tasks: config.yml
- include_tasks: root-password.yml
- include_tasks: databases.yml
- include_tasks: users.yml
