---

- name: Copy uwsgi service master file
  template: 
    src:  uwsgi.service.j2 
    dest: /etc/systemd/system/uwsgi.service

- name: Ensure project directory exists
  file: 
    path: /etc/uwsgi.d
    state: directory

- name: Copy uwsgi configuration file of project
  template: 
    src:  uwsgi.j2 
    dest: /etc/uwsgi.d/{{ project_name }}.ini

- name: Restart service uwsgi and also issue daemon-reload to pick up config changes
  systemd:
    name: uwsgi
    state: restarted
    daemon_reload: yes
    enabled: true